// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: ingestion.proto

package ingestionv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/raftweave/backend/api/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IngestionServiceName is the fully-qualified name of the IngestionService service.
	IngestionServiceName = "raftweave.ingestion.v1.IngestionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IngestionServiceReceiveWebhookProcedure is the fully-qualified name of the IngestionService's
	// ReceiveWebhook RPC.
	IngestionServiceReceiveWebhookProcedure = "/raftweave.ingestion.v1.IngestionService/ReceiveWebhook"
)

// IngestionServiceClient is a client for the raftweave.ingestion.v1.IngestionService service.
type IngestionServiceClient interface {
	// ReceiveWebhook accepts a verified, deduplicated, rate-limited webhook
	// event for further processing.
	ReceiveWebhook(context.Context, *connect.Request[proto.WebhookEvent]) (*connect.Response[proto.WebhookAck], error)
}

// NewIngestionServiceClient constructs a client for the raftweave.ingestion.v1.IngestionService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIngestionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IngestionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	ingestionServiceMethods := proto.File_ingestion_proto.Services().ByName("IngestionService").Methods()
	return &ingestionServiceClient{
		receiveWebhook: connect.NewClient[proto.WebhookEvent, proto.WebhookAck](
			httpClient,
			baseURL+IngestionServiceReceiveWebhookProcedure,
			connect.WithSchema(ingestionServiceMethods.ByName("ReceiveWebhook")),
			connect.WithClientOptions(opts...),
		),
	}
}

// ingestionServiceClient implements IngestionServiceClient.
type ingestionServiceClient struct {
	receiveWebhook *connect.Client[proto.WebhookEvent, proto.WebhookAck]
}

// ReceiveWebhook calls raftweave.ingestion.v1.IngestionService.ReceiveWebhook.
func (c *ingestionServiceClient) ReceiveWebhook(ctx context.Context, req *connect.Request[proto.WebhookEvent]) (*connect.Response[proto.WebhookAck], error) {
	return c.receiveWebhook.CallUnary(ctx, req)
}

// IngestionServiceHandler is an implementation of the raftweave.ingestion.v1.IngestionService
// service.
type IngestionServiceHandler interface {
	// ReceiveWebhook accepts a verified, deduplicated, rate-limited webhook
	// event for further processing.
	ReceiveWebhook(context.Context, *connect.Request[proto.WebhookEvent]) (*connect.Response[proto.WebhookAck], error)
}

// NewIngestionServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIngestionServiceHandler(svc IngestionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ingestionServiceMethods := proto.File_ingestion_proto.Services().ByName("IngestionService").Methods()
	ingestionServiceReceiveWebhookHandler := connect.NewUnaryHandler(
		IngestionServiceReceiveWebhookProcedure,
		svc.ReceiveWebhook,
		connect.WithSchema(ingestionServiceMethods.ByName("ReceiveWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	return "/raftweave.ingestion.v1.IngestionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IngestionServiceReceiveWebhookProcedure:
			ingestionServiceReceiveWebhookHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIngestionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIngestionServiceHandler struct{}

func (UnimplementedIngestionServiceHandler) ReceiveWebhook(context.Context, *connect.Request[proto.WebhookEvent]) (*connect.Response[proto.WebhookAck], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("raftweave.ingestion.v1.IngestionService.ReceiveWebhook is not implemented"))
}
