// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ingestion.proto

package ingestionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WebhookEvent represents a single push event received from a source code
// host (GitHub or GitLab) after transport-level verification.
type WebhookEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "github" or "gitlab".
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// Stable identifier for the repository the event originated from,
	// used as the dedup/rate-limit scope key.
	RepoId string `protobuf:"bytes,2,opt,name=repo_id,json=repoId,proto3" json:"repo_id,omitempty"`
	// Unique delivery identifier supplied by the provider
	// (X-GitHub-Delivery for GitHub, generated for GitLab) used for replay
	// detection.
	DeliveryId string `protobuf:"bytes,3,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	// Raw JSON payload of the webhook body.
	Payload []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	// Commit SHA the event refers to, when available.
	CommitSha     string `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEvent) Reset() {
	*x = WebhookEvent{}
	mi := &file_ingestion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEvent) ProtoMessage() {}

func (x *WebhookEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEvent.ProtoReflect.Descriptor instead.
func (*WebhookEvent) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{0}
}

func (x *WebhookEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *WebhookEvent) GetRepoId() string {
	if x != nil {
		return x.RepoId
	}
	return ""
}

func (x *WebhookEvent) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *WebhookEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WebhookEvent) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

// WebhookAck is returned to the caller once a webhook event has been
// accepted for processing.
type WebhookAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,2,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookAck) Reset() {
	*x = WebhookAck{}
	mi := &file_ingestion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookAck) ProtoMessage() {}

func (x *WebhookAck) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookAck.ProtoReflect.Descriptor instead.
func (*WebhookAck) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *WebhookAck) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

// ResourceSpec describes the compute resources requested for a workload.
type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores int32                  `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryMib     int32                  `protobuf:"varint,2,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_ingestion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceSpec) GetCpuMillicores() int32 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceSpec) GetMemoryMib() int32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

// DatabaseSpec describes the managed database requested for a workload.
type DatabaseSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseSpec) Reset() {
	*x = DatabaseSpec{}
	mi := &file_ingestion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseSpec) ProtoMessage() {}

func (x *DatabaseSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseSpec.ProtoReflect.Descriptor instead.
func (*DatabaseSpec) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{3}
}

func (x *DatabaseSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DatabaseSpec) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// WorkloadSpec is the parsed and validated representation of a
// raftweave.yaml workload descriptor.
type WorkloadSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadName  string                 `protobuf:"bytes,1,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	PrimaryCloud  string                 `protobuf:"bytes,2,opt,name=primary_cloud,json=primaryCloud,proto3" json:"primary_cloud,omitempty"`
	StandbyClouds []string               `protobuf:"bytes,3,rep,name=standby_clouds,json=standbyClouds,proto3" json:"standby_clouds,omitempty"`
	PrimaryRegion string                 `protobuf:"bytes,4,opt,name=primary_region,json=primaryRegion,proto3" json:"primary_region,omitempty"`
	ComputeType   string                 `protobuf:"bytes,5,opt,name=compute_type,json=computeType,proto3" json:"compute_type,omitempty"`
	Resources     *ResourceSpec          `protobuf:"bytes,6,opt,name=resources,proto3" json:"resources,omitempty"`
	Database      *DatabaseSpec          `protobuf:"bytes,7,opt,name=database,proto3" json:"database,omitempty"`
	Dependencies  []string               `protobuf:"bytes,8,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_ingestion_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ingestion_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_ingestion_proto_rawDescGZIP(), []int{4}
}

func (x *WorkloadSpec) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *WorkloadSpec) GetPrimaryCloud() string {
	if x != nil {
		return x.PrimaryCloud
	}
	return ""
}

func (x *WorkloadSpec) GetStandbyClouds() []string {
	if x != nil {
		return x.StandbyClouds
	}
	return nil
}

func (x *WorkloadSpec) GetPrimaryRegion() string {
	if x != nil {
		return x.PrimaryRegion
	}
	return ""
}

func (x *WorkloadSpec) GetComputeType() string {
	if x != nil {
		return x.ComputeType
	}
	return ""
}

func (x *WorkloadSpec) GetResources() *ResourceSpec {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkloadSpec) GetDatabase() *DatabaseSpec {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *WorkloadSpec) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

var File_ingestion_proto protoreflect.FileDescriptor

const file_ingestion_proto_rawDesc = "" +
	"\n" +
	"\x0fingestion.proto\x12\x16raftweave.ingestion.v1\"\x9d\x01\n" +
	"\fWebhookEvent\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x17\n" +
	"\arepo_id\x18\x02 \x01(\tR\x06repoId\x12\x1f\n" +
	"\vdelivery_id\x18\x03 \x01(\tR\n" +
	"deliveryId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\"I\n" +
	"\n" +
	"WebhookAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vdelivery_id\x18\x02 \x01(\tR\n" +
	"deliveryId\"T\n" +
	"\fResourceSpec\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x05R\rcpuMillicores\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x02 \x01(\x05R\tmemoryMib\"<\n" +
	"\fDatabaseSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xf3\x02\n" +
	"\fWorkloadSpec\x12#\n" +
	"\rworkload_name\x18\x01 \x01(\tR\fworkloadName\x12#\n" +
	"\rprimary_cloud\x18\x02 \x01(\tR\fprimaryCloud\x12%\n" +
	"\x0estandby_clouds\x18\x03 \x03(\tR\rstandbyClouds\x12%\n" +
	"\x0eprimary_region\x18\x04 \x01(\tR\rprimaryRegion\x12!\n" +
	"\fcompute_type\x18\x05 \x01(\tR\vcomputeType\x12B\n" +
	"\tresources\x18\x06 \x01(\v2$.raftweave.ingestion.v1.ResourceSpecR\tresources\x12@\n" +
	"\bdatabase\x18\a \x01(\v2$.raftweave.ingestion.v1.DatabaseSpecR\bdatabase\x12\"\n" +
	"\fdependencies\x18\b \x03(\tR\fdependencies2n\n" +
	"\x10IngestionService\x12Z\n" +
	"\x0eReceiveWebhook\x12$.raftweave.ingestion.v1.WebhookEvent\x1a\".raftweave.ingestion.v1.WebhookAckB4Z2github.com/raftweave/backend/api/proto;ingestionv1b\x06proto3"

var (
	file_ingestion_proto_rawDescOnce sync.Once
	file_ingestion_proto_rawDescData []byte
)

func file_ingestion_proto_rawDescGZIP() []byte {
	file_ingestion_proto_rawDescOnce.Do(func() {
		file_ingestion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)))
	})
	return file_ingestion_proto_rawDescData
}

var file_ingestion_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ingestion_proto_goTypes = []any{
	(*WebhookEvent)(nil), // 0: raftweave.ingestion.v1.WebhookEvent
	(*WebhookAck)(nil),   // 1: raftweave.ingestion.v1.WebhookAck
	(*ResourceSpec)(nil), // 2: raftweave.ingestion.v1.ResourceSpec
	(*DatabaseSpec)(nil), // 3: raftweave.ingestion.v1.DatabaseSpec
	(*WorkloadSpec)(nil), // 4: raftweave.ingestion.v1.WorkloadSpec
}
var file_ingestion_proto_depIdxs = []int32{
	2, // 0: raftweave.ingestion.v1.WorkloadSpec.resources:type_name -> raftweave.ingestion.v1.ResourceSpec
	3, // 1: raftweave.ingestion.v1.WorkloadSpec.database:type_name -> raftweave.ingestion.v1.DatabaseSpec
	0, // 2: raftweave.ingestion.v1.IngestionService.ReceiveWebhook:input_type -> raftweave.ingestion.v1.WebhookEvent
	1, // 3: raftweave.ingestion.v1.IngestionService.ReceiveWebhook:output_type -> raftweave.ingestion.v1.WebhookAck
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ingestion_proto_init() }
func file_ingestion_proto_init() {
	if File_ingestion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ingestion_proto_rawDesc), len(file_ingestion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ingestion_proto_goTypes,
		DependencyIndexes: file_ingestion_proto_depIdxs,
		MessageInfos:      file_ingestion_proto_msgTypes,
	}.Build()
	File_ingestion_proto = out.File
	file_ingestion_proto_goTypes = nil
	file_ingestion_proto_depIdxs = nil
}
